- firestore.rules
- src/app/delete-dialog/delete-dialog.component.html
- src/app/delete-dialog/delete-dialog.component.ts
- src/app/mypage/mypage/mypage.component.html
- src/app/mypage/mypage/mypage.component.scss
- src/app/mypage/mypage/mypage.component.ts
- src/app/profile/profile/profile.component.html
- src/app/profile/profile/profile.component.ts
- src/app/service/user-profile.service.ts
- ユーザープロフィールを削除ボタンを押すと削除できるようにしました。
- マイページでプロフィールがない時にはdefault textとプロフィール作成ボタンを表示。
レビューよろしくお願いいたします。
> Feature/108 ユーザープロフィール/Firestoreから削除

- src/app/company-profile/company-profile/company-profile.component.html
- src/app/company-profile/company-profile/company-profile.component.scss
- src/app/company-profile/company-profile/company-profile.component.ts
- src/app/delete-dialog/delete-dialog.component.html
- src/app/delete-dialog/delete-dialog.component.ts
- src/app/mypage/mypage/mypage.component.ts
- src/app/service/company-profile.service.ts
- 企業側のFirestoreのプロフィール削除
- プロフィールが存在しない時はdefaultのテキストと作成ボタン配置
- dialogのdelete関数をコンポーネントごとに分割
レビューよろしくお願いいたします！！
> Feature/new122 企業側Firestore削除、メソッド分割

- src/app/create-company-profile/register-form/register-form.component.ts
- src/app/create-user-profile/profile/profile.component.html
- src/app/create-user-profile/profile/profile.component.ts
- 片方で登録していたらもう一方では登録させないという実装でしたが両方に登録していなくてもプロフィールが作成されない実装になっていたので修正いたしました。
ログイン⇨プロフィール登録の手順で確認済みです。
- Formの生年月日の出力時に日付がずれていたので修正しました。
PR多くてお手数お掛け致しますがよろしくお願い致します。
> Feature/201 submit関数コード修正

- src/app/header/header.component.ts
- src/app/services/auth.service.ts
- header-menuの出し分けでページリロードするとmenuの内容が変わってしまうというバグが生じていたのでログイン状態をlocalstorageで管理に変更しました。
> fix(header): メニュー切り替え（localstorage)追加実装 #202

- src/app/detail/detail/detail.component.scss
- #245 GoogleMapの表示崩れ
- GoogleMap幅修正しました。
[![Image from Gyazo](https://i.gyazo.com/d3bbf42c1d0d948fc5d9e04e569d277c.gif)](https://gyazo.com/d3bbf42c1d0d948fc5d9e04e569d277c)
> GoogleMap幅修正 #245

- src/app/header/header.component.html
- #248 ログアウト後もアイコンボタンが表示される
- ログアウト後にメニューが非表示になっていてもクリックできてしまっていたので、クリックできない実装にしました。
- ログイン後はクリックしても何も起きません。
[![Image from Gyazo](https://i.gyazo.com/4e8b0866de0985ae97623fef11473569.gif)](https://gyazo.com/4e8b0866de0985ae97623fef11473569)
> ログイン後headerのmenuにクリックできないようにする実装 #248

- src/styles/_job-post.scss
- #242 カードスタイル調整
- 求人カードにpadding: 16px追加
> 求人カードにpadding追加 #242

- src/app/intl/help/help.component.html
- #234 メール送信は別タブで開きたい
- メーラーを別タブで開く実装
> メーラーを別タブで開く実装 #234

- src/app/header/header.component.html
- #237 マイページと自社求人がメニューに表示されている
- headerのメニュー名を変更
変更前
変更後
> headerのmenu名変更 #237

- src/app/stripe/stripe/stripe.component.html
- #238 文言修正
- 有料プラン登録画面のボタンの文言修正 「購入する」➡️　「登録する」に変更。
> 有料プラン登録画面のボタンの文言修正 #238

- src/app/create-company-profile/company-side.module.ts
- src/app/create-company-profile/register-form/register-form.component.html
- src/app/create-user-profile/profile.module.ts
- src/app/create-user-profile/profile/profile.component.html
- src/app/recruitment/form.module.ts
- src/app/recruitment/recruitment/recruitment.component.html
- src/styles/_profile-form.scss
- #265 求人作成のデザイン調整
- 求人作成
- 企業登録
- ユーザー
Formにmat-card追加
> Form関連にmat-card追加 #265

- src/styles/_job-post.scss
- #284 グリッドの幅を検討する
- cardのmargin-bottomを縮小しました。
> グリッド(margin-bottm)縮小#284

- src/app/app.component.scss
- src/app/header/header.component.scss
- #301 headerデザイン修正
- headerテキストカラー変更
- サイドバーmargin変更
> header/スタイル壊れているところの修正 #301

- src/app/app.module.ts
- src/app/auth-dialog/auth-dialog.component.html
- src/app/auth-dialog/auth-dialog.component.scss
- src/app/auth-dialog/auth-dialog.component.spec.ts
- src/app/auth-dialog/auth-dialog.component.ts
- src/app/header/header.component.html
- src/app/header/header.component.ts
- src/app/services/auth.service.ts
- #276 ログインボタンをheaderに置く
- ログインボタンを headerに配置
- ログインダイアログ追加
- ダイアログでのログイン状態をheaderのmenuに反映
> ログインボタンheaderに配置/ ログインダイアログ追加

- src/app/plan/plan/plan.component.html
- src/app/stripe/stripe/stripe.component.html
- #236 プラン登録押しても何も起きない
- プランの初期状態は無料プランの方に登録中
- 有料プランに変更すると無料プランの文言が登録に変わる。
> 無料プランのボタンdisabled追加、ボタン文言追加 

- src/app/header/header.component.ts
- src/app/services/auth.service.ts
- #263 未ログイン時も求人作成ボタンが表示されている
- 退会後も求人作成ボタンが表示されていたので、退会時にもlocalStorageの値を削除しました。
[![Image from Gyazo](https://i.gyazo.com/bdfdd3d3cf1a5868a00f519a2a8e40a4.gif)](https://gyazo.com/bdfdd3d3cf1a5868a00f519a2a8e40a4)
> 退会時にもlocalStorage削除で求人作成ボタンを非表示にする #263

- src/app/plan/plan/plan.component.html
- src/app/plan/plan/plan.component.scss
- src/app/plan/plan/plan.component.ts
- #271 stripe/課金開始日時を記録しておく
- 決済情報を追加
- サブスク開始日時を記録
- していなければ「決済情報はありません」追加
> 決済履歴追加 #271

- src/app/app.component.html
- #330 Footer/修正
- サイドナビ開閉時にFooterが前に出てきてしまっていたバグの修正
変更前
> Footer 修正 #330

- src/styles/_job-post.scss
- #332 (card) Gridの幅修正
- cardの幅を調整しました。
変更前
> grid幅スタイル調整 #332

- src/app/header/header.component.html
- src/app/header/header.component.ts
- #310 課金したときの処理を考え・作成する
- 投稿数が一件以上あるか、一件もない、プレミアムプランに登録していたら求人作成
- 投稿数が一件以上あって課金IDが存在しない場合はsnackbar表示
> 投稿数に応じて処理分岐 #310
