- src/app/app.component.html
- src/app/app.module.ts
- src/app/form/recruitment/recruitment.component.html
- src/app/form/recruitment/recruitment.component.ts
- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/services/auth.service.ts
- src/styles.scss
- snackbar表示
- Form、maxLenght追加
- header,footerスタイル変更
> スナックバー表示、他諸々

- src/app/services/auth.service.ts
> feat(auth): Google認証に変更 #45

- firebase.json
- firestore.indexes.json
- firestore.rules
- storage.rules
> fix(firebase): Firebase初期化 #37

- src/app/company-side/register-form/register-form.component.html
- src/app/company-side/register-form/register-form.component.ts
- src/app/services/auth.service.ts
- ログアウトするとトップページにリダイレクト
- ログインして企業側のページに飛んだ時にログインとは別のForm（前に作成したもの）は必要か？いらなければ消去。
確認お願いいたします！！
> feat(register-form): ログアウト機能追加、リンク追加 #43

- .prettierrc
- package-lock.json
- package.json
> feat(package.json): Prettier追加 #60

- src/app/app-routing.module.ts
- src/app/mypage/mypage-routing.module.ts
- src/app/mypage/mypage.module.ts
- src/app/mypage/mypage/mypage.component.html
- src/app/mypage/mypage/mypage.component.scss
- src/app/mypage/mypage/mypage.component.spec.ts
- src/app/mypage/mypage/mypage.component.ts
> feat(mypage): ページ作成、マークアップ #66

- src/app/app.module.ts
- src/app/delete-dialog/delete-dialog.component.html
- src/app/delete-dialog/delete-dialog.component.scss
- src/app/delete-dialog/delete-dialog.component.spec.ts
- src/app/delete-dialog/delete-dialog.component.ts
- src/app/mypage/mypage/mypage.component.html
- src/app/mypage/mypage/mypage.component.scss
- src/app/mypage/mypage/mypage.component.ts
- ダイアログ
- 利用規約諸々追加
---
レビューお願い致します。
> feat(mypage): mypage作成、ダイアログ作成 #66

- src/app/app.component.html
- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/services/auth.service.ts
- src/styles.scss
- headerのフォントサイズ、ボタン
- footerのスタイル調整
grid-template-columns: 4 1fr;四分割？にしたんですが縦並びのままでした
---
user$ === ' 'なら、 user$ === trueなどやりました。
あと、AngularだとtsでStyle属性でdisplay: noneとかclassの付け替えとかしたらいいのかな？とかんがえました。
レビューお願い致します。
> style(header,footer): UI調整 #63

- src/app/app-routing.module.ts
- src/app/create-review/create-review-routing.module.ts
- src/app/create-review/create-review.module.ts
- src/app/create-review/create-review/create-review.component.html
- src/app/create-review/create-review/create-review.component.scss
- src/app/create-review/create-review/create-review.component.spec.ts
- src/app/create-review/create-review/create-review.component.ts
- src/app/detail/detail.module.ts
- src/app/detail/review/review.component.html
- src/app/detail/review/review.component.scss
- src/app/detail/review/review.component.ts
- レビュー投稿ページ追加
- 使われていないtsのコード削除
- 詳細ページのreview欄Progress barに変更
- レビュー投稿ページのForm作成、consoleでvalue取得完了
---
---
レビューよろしくお願い致します。
> Feature/39 レビューページ追加/未使用コード削除/Form追加

- src/app/company-side/register-form/register-form.component.html
- src/app/company-side/register-form/register-form.component.ts
- src/app/detail/detail/detail.component.html
- src/app/detail/detail/detail.component.ts
- src/app/interfaces/article.ts
- src/app/interfaces/profile.ts
- src/app/joblist/joblist/joblist.component.html
- src/app/joblist/joblist/joblist.component.ts
- src/app/profile/profile/profile.component.html
- src/app/profile/profile/profile.component.ts
- src/app/top/attention/attention.component.ts
- src/app/top/new/new.component.ts
- 各コンポーネントのインターフェイス定義
- コードの編集
> Feature/35 インターフェイス追加、コード整理

- src/app/not-found/not-found.component.html
- src/app/not-found/not-found.component.scss
- src/app/not-found/not-found.module.ts
- トップへ戻るボタン、リンク追加
レビューお願い致します。
> feat(not-found): 404ページ/トップへ戻るボタン追加 #50

- src/app/profile/profile/profile.component.html
- src/app/profile/profile/profile.component.ts
> fix(profile): profileページerror修正 #83

- src/app/top/attention/attention.component.html
- src/app/top/attention/attention.component.scss
- src/app/top/attention/attention.component.ts
- src/app/top/new/new.component.html
- new、attentionでエラーが出ていた箇所を修正しました。
お願い致します
> fix(new,attention): エラー修正 #80

- firestore.rules
- src/app/company-side/register-form/register-form.component.html
- src/app/company-side/register-form/register-form.component.ts
- src/app/form/recruitment/recruitment.component.html
- src/app/form/recruitment/recruitment.component.ts
- src/app/interfaces/article.ts
- src/app/interfaces/profile.ts
- src/app/profile/profile/profile.component.html
- src/app/profile/profile/profile.component.ts
- src/app/service/company-profile.service.spec.ts
- src/app/service/company-profile.service.ts
- src/app/service/job-post.service.spec.ts
- src/app/service/job-post.service.ts
- src/app/service/user-profile.service.spec.ts
- src/app/service/user-profile.service.ts
- src/app/services/auth.service.ts
- profile(user/company)データ保存
- 求人の投稿のデータ保存
* 画像アップロードまだやっていないので、interfaceダミーで定義してあるところがあります。
レビューお願いします！
> Feature/69 データをFireStoreに保存

- src/app/mypage/mypage/mypage.component.html
- src/app/mypage/mypage/mypage.component.ts
- src/app/profile/profile/profile.component.ts
- src/app/service/user-profile.service.ts
> feat(mypage): Fire storeからの値の取り出し・表示 #86

- src/app/app-routing.module.ts
- src/app/company-profile/company-profile-routing.module.ts
- src/app/company-profile/company-profile.module.ts
- src/app/company-profile/company-profile/company-profile.component.html
- src/app/company-profile/company-profile/company-profile.component.scss
- src/app/company-profile/company-profile/company-profile.component.spec.ts
- src/app/company-profile/company-profile/company-profile.component.ts
- src/app/company-side/register-form/register-form.component.html
- src/app/company-side/register-form/register-form.component.ts
- src/app/interfaces/profile.ts
- src/app/service/company-profile.service.ts
- マークアップ・スタイル
- FireStore値取り出し、表示
- pathchValue追加
レビューお願い致します！
> Feature/89 企業側登録/Firestore値取り出し、表示

- src/app/joblist/joblist/joblist.component.html
- src/app/joblist/joblist/joblist.component.ts
- src/app/keep/keep/keep.component.html
- src/app/keep/keep/keep.component.ts
- src/app/service/job-post.service.ts
- src/app/top/attention/attention.component.html
- src/app/top/attention/attention.component.ts
- src/app/top/new/new.component.html
- src/app/top/new/new.component.ts
Firestoreデータ表示
- トップページ
- お気に入りページ
- 求人一覧ページ
忘れそうなのでプルリクしておきます。
> Feature/99 Firestoreデータ表示各ページ

- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/services/auth.service.ts
- ログイン時にheaderにdisplayName表示しました。
＊Style,headerマークアップなど諸々別issueにて修正します。
レビューお願いします。
> feat(header): displayName表示 #79

- firestore.rules
- src/app/create-review/create-review/create-review.component.ts
- src/app/detail/review/review.component.html
- src/app/detail/review/review.component.scss
- src/app/detail/review/review.component.ts
- src/app/interfaces/review.ts
- src/app/service/review.service.spec.ts
- src/app/service/review.service.ts
- レビューページのデータ表示、グラフパーセンテージの反映
- レビューページの青のborder-left 削除
よろしくお願いします。
> feat(review):  reviewデータ表示 #92

- src/app/detail/detail/detail.component.html
- src/app/detail/detail/detail.component.ts
- src/app/form/recruitment/recruitment.component.ts
- src/app/interfaces/article.ts
- 求人投稿の公開日を取得・表示しました。
レビューお願いいたします。
> Feature/100 投稿の公開日取得

- src/app/app.component.html
- src/app/company-side/company-side.module.ts
- src/app/company-side/register-form/register-form.component.html
- src/app/company-side/register-form/register-form.component.scss
- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/legal/terms/terms.component.scss
- src/app/search/search.component.html
- src/app/search/search.component.scss
- src/app/top/attention/attention.component.scss
- src/app/top/attention/attention.component.ts
- src/app/top/new/new.component.scss
- src/app/top/top/top.component.html
- src/app/top/top/top.component.scss
- src/styles.scss
全体的なスタイル調整を行いました。
トップページ、企業側のプロフィール作成ページ利用規約追加
レビューお願いいたします。
> Feature/96 UI調整

- src/app/detail/detail-routing.module.ts
- src/app/detail/detail/detail.component.html
- src/app/detail/detail/detail.component.ts
- src/app/form/recruitment/recruitment.component.html
- src/app/form/recruitment/recruitment.component.ts
- src/app/interfaces/article.ts
- src/app/service/job-post.service.ts
> Feature/112 複数画像アップロード、投稿id取得

- src/app/detail/detail.module.ts
- src/app/detail/detail/detail.component.html
- src/app/detail/detail/detail.component.scss
- src/app/detail/detail/detail.component.ts
- src/app/service/job-post.service.ts
- 投稿の削除
- ダイアログ追加
レビューよろしくお願いいたします
> Feature/n 109 求人投稿/firestore削除

- src/app/detail/detail/detail.component.html
- src/app/detail/detail/detail.component.ts
- src/app/service/job-post.service.ts
- src/app/top/attention/attention.component.html
- src/app/top/attention/attention.component.ts
- src/app/top/new/new.component.html
- src/app/top/new/new.component.ts
投稿をクリックした時に指定の求人に遷移できるようになっています。
Attentionの方はダミーで作っています。
レビューよろしくお願い致します
> Feature/107 新着求人の表示条件、リンク変更

- src/app/joblist/joblist/joblist.component.html
- src/app/joblist/joblist/joblist.component.ts
- src/app/service/job-post.service.ts
- 求人一覧ページの表示条件を実装
- ページ遷移にidを付与
よろしくお願い致します。
> feat(joblist): 求人一覧の表示条件実装 #134

- src/app/header/header.component.html
- src/app/header/header.component.scss
- user image をmat-buttonからmat-iconボタンに変更
- header横幅にpadding追加
- displayName, email削除
よろしくお願いいたします
> Feature/123 headerUI調整

- src/app/company-side/company-side-routing.module.ts
- src/app/company-side/register-form/register-form.component.ts
- src/app/form/form-routing.module.ts
- src/app/form/recruitment/recruitment.component.ts
複数の編集Guard追加
レビューよろしくお願いいたします。
> Feature/138 2 求人投稿/企業側フォーム 編集Guard追加

- src/app/detail/detail/detail.component.html
- src/app/form/recruitment/recruitment.component.html
- src/app/form/recruitment/recruitment.component.scss
- src/app/form/recruitment/recruitment.component.ts
- src/app/header/header.component.html
- src/app/service/job-post.service.ts
- src/app/top/attention/attention.component.scss
- 求人作成フォームpatchvalue追加
- 編集画面で画像が存在したら画像を表示
- 求人記事update関数追加
- headerに求人作成アイコンボタン追加
昨日はありがとうございました。
レビューよろしくお願いいたします。
> Feature/139 patchValue追加、update関数追加etc

- src/app/service/job-post.service.ts
> feat(job-post.service): 注目求人いいねが多い順に表示 #106

- src/app/top/top/top.component.scss
- src/styles/_reset.scss
- 見出しをfont-weight: 500に統一
よろしくお願いいたします。
> refactor(top, reset): 見出しfont-weight: 500に統一 #150

- src/app/app.module.ts
- src/app/joblist/joblist/joblist.component.html
- src/app/keep/keep/keep.component.html
- src/app/top/attention/attention.component.scss
- src/app/top/new/new.component.html
- src/app/top/new/new.component.scss
- src/app/top/top/top.component.html
- src/app/top/top/top.component.scss
- src/styles/_job-card.scss
- src/styles/_reset.scss
- max-width追加
- h1タグ追加
- スタイル調整
よろしくお願い致します。
> Feature/159 トップページスタイル変更

- src/app/app-routing.module.ts
- src/app/company-job-list/company-job-list-routing.module.ts
- src/app/company-job-list/company-job-list.module.ts
- src/app/company-job-list/company-job-list/company-job-list.component.html
- src/app/company-job-list/company-job-list/company-job-list.component.scss
- src/app/company-job-list/company-job-list/company-job-list.component.spec.ts
- src/app/company-job-list/company-job-list/company-job-list.component.ts
- src/app/services/job-post.service.ts
> feat(company-job-list): 自社の求人一覧表示 #168

- src/app/detail/detail/detail.component.html
- src/app/detail/detail/detail.component.scss
- src/app/detail/detail/detail.component.ts
- src/app/joblist/joblist.module.ts
- src/app/joblist/joblist/joblist.component.html
- src/app/joblist/joblist/joblist.component.scss
- src/app/keep/keep/keep.component.html
- src/app/services/job-post.service.ts
- src/app/services/liked.service.ts
- src/index.html
- src/styles/_job-card.scss
-  詳細ページでのいいね機能実装
レビューよろしくお願いいたします。
> Feature/144 フロント側のいいね実装

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/home/search/search.component.html
- src/app/home/search/search.component.ts
- src/app/home/top.module.ts
- src/app/search-input/search-input.component.html
- src/app/search-input/search-input.component.spec.ts
- src/app/search-input/search-input.component.ts
- src/app/search-result/search-result.component.html
- src/app/search-result/search-result.component.scss
- src/app/search-result/search-result.component.spec.ts
- src/app/search-result/search-result.component.ts
- src/styles.scss
- アルゴリアAngular Material導入
- 検索候補表示
- 検索結果ページ作成
- 検索結果がなければテキストを表示
＊UI調整と、headerでの検索は後ほどのisssueで行います。
ご確認よろしくお願いいたします。
---
> Feature/175 アルゴリア機能追加

- src/app/app-routing.module.ts
- src/app/app.component.html
- src/app/header/header.component.html
- src/app/help/help-routing.module.ts
- src/app/help/help.module.ts
- src/app/help/help/help.component.html
- src/app/help/help/help.component.scss
- src/app/help/help/help.component.spec.ts
- src/app/help/help/help.component.ts
- src/styles.scss
- footer,header link,iconの整理
- ヘルプページ作成
ご確認よろご確認よろしくお願い致します。
> Feature/187 設定ページの整理、ヘルプページ追加

- src/app/about/about/about.component.scss
- src/app/app.component.html
- src/app/detail/detail/detail.component.html
- src/app/detail/detail/detail.component.scss
- src/app/home/attention/attention.component.scss
- src/app/home/new/new.component.html
- src/app/home/new/new.component.scss
- src/app/home/top/top.component.scss
- src/app/joblist/joblist/joblist.component.html
- src/app/keep/keep/keep.component.html
- src/app/keep/keep/keep.component.scss
- src/app/legal/terms/terms.component.scss
- src/app/plan/plan/plan.component.html
- src/app/privacy/privacy/privacy.component.scss
- src/styles.scss
- src/styles/_job-card.scss
- src/styles/_profiles-card.scss
- h1の下にborder-bottom追加
- 注目求人の記事にhoverするとcardが浮き上がるアニメーション実装
> Feature/26 UI調整

- src/app/app.module.ts
- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/header/header.component.ts
- src/app/home/search/search.component.ts
- src/app/home/top.module.ts
- src/app/home/top/top.component.html
- src/app/search-input/search-input.component.html
- src/styles.scss
- headerに検索機能追加
- トップページにはアイコンを非表示
> feat(header): 検索機能追加 #183

- firestore.rules
- src/app/interfaces/card.ts
- src/app/plan/plan.module.ts
- src/app/plan/plan/plan.component.html
- src/app/plan/plan/plan.component.scss
- src/app/plan/plan/plan.component.ts
- src/app/services/fee.service.ts
- src/app/stripe/payment/payment.component.ts
- src/app/stripe/stripe/stripe.component.ts
- src/index.html
- Card情報を追加とCardの種類によってFontAwesom変更
- Firestoreにカード情報の一部を保存
> Feature/186 PlanページCard情報記載の実装

- firestore.rules
> Feature/136 Firestore.rules追加

- firestore.rules
- src/app/keep/keep/keep.component.html
- src/app/keep/keep/keep.component.ts
- お気に入りページの件数表示
- 求人詳細ページのリンク追加
- エラーfix
> Feature/203 お気に入り件数表示とエラーfix

- src/styles.scss
> style(styles.scss): margin-bottm追加 #199

- src/app/company-job-list/company-job-list/company-job-list.component.html
- src/app/header/header.component.html
- src/app/keep/keep/keep.component.html
- src/app/keep/keep/keep.component.scss
- src/styles/_job-card.scss
- 自社投稿一覧ページに求人投稿した件数を表示
- 自社投稿ページへのリンク追加（header menu)
> Feature/198  自社投稿ページへのリンク追加と件数表示

- src/app/create-company-profile/register-form/register-form.component.ts
- src/app/create-user-profile/profile/profile.component.ts
- src/app/profile-dialog/profile-dialog.component.html
- src/app/profile-dialog/profile-dialog.component.ts
- src/app/recruitment/recruitment/recruitment.component.ts
- プロフィール作成していないと求人を作成できないようにする実装。
- ダイアログの統一化。
> Feature/221 プロフィール作成していないと求人を作成できないようにする。

- src/app/services/auth.service.ts
- src/app/services/company-profile.service.ts
- src/app/services/job-post.service.ts
- src/app/services/user-profile.service.ts
> feat(services): error処理追加 #217

- src/app/home/attention/attention.component.html
- src/app/home/new/new.component.html
- src/app/home/top/top.component.scss
- src/styles/_job-post.scss
> feat(home): cardの高さ統一 #205

- src/app/app.component.ts
- src/app/detail/detail/detail.component.ts
> feat(app, detail): ogp取得 #185

- src/app/app.component.html
- src/app/detail/detail/detail.component.html
- src/app/detail/detail/detail.component.ts
- src/app/intl/about/about.component.scss
- src/app/intl/help/help.component.scss
- src/app/intl/privacy/privacy.component.scss
- src/app/intl/terms/terms.component.scss
- src/app/recruitment/recruitment/recruitment.component.html
- src/styles/_profiles-card.scss
- 求人作成ページFormの値がないときにはdisabled追加
- 求人を削除したらトップページに飛ばす
-Formの値でlabelがない時にはcssのスタイルをnoneにする
- タイトルの高さを統一
> Feature/226 全体の細かいところの修正

- src/app/app.component.scss
- src/app/services/auth.service.ts
> refactor(app): padding削除 #231

- src/app/header/header.component.html
- #240 +ボタンの説明と挙動を改善する
- header求人作成ボタン、検索ボタンにツールチップ追加
- 企業側でログインのみ＋ボタン追加
[![Image from Gyazo](https://i.gyazo.com/304042ee173754a523376fd1e9e291de.gif)](https://gyazo.com/304042ee173754a523376fd1e9e291de)
> header求人作成ボタン、検索ボタンにツールチップ追加 #240

- src/app/joblist/joblist/joblist.component.html
- src/app/services/auth.service.ts
- src/styles/_job-card.scss
- #232  ホバーした時の挙動
- カードに対して全体をrouterLinkで囲い全体をクリックできるように修正しました。
[![Image from Gyazo](https://i.gyazo.com/1ce3da8c7d3260da7a21fc1c9727b361.gif)](https://gyazo.com/1ce3da8c7d3260da7a21fc1c9727b361)
> 求人カードに対してカード全体をクリックする実装

- src/app/app-routing.module.ts
- #268 routingエラー
- conflictを間違えて取り込んでしまったためbuildエラーが発生してしまったので解消しました。
なし
ご確認よろしくお願いいたします。
> Routingエラー修正 #268

- src/app/search-result/search-result.component.html
- #278 検索結果が見つからなかった時にnullになる
- 検索結果nullを修正しました。
fix #22
> 検索結果nullを修正 #278

- src/app/app-routing.module.ts
- src/app/app.component.html
- src/app/company-job-list/company-job-list/company-job-list.component.html
- src/app/company-profile/company-profile/company-profile.component.html
- src/app/detail/detail/detail.component.html
- src/app/footer/footer.component.html
- src/app/header/header.component.html
- src/app/home/attention/attention.component.html
- src/app/home/new/new.component.html
- src/app/home/top/top.component.html
- src/app/job-list/job-list/job-list.component.html
- src/app/keep/keep/keep.component.html
- src/app/mypage/mypage/mypage.component.html
- src/app/search-result/search-result.component.html
- src/app/services/auth.service.ts
- src/app/services/company-profile.service.ts
- src/app/services/job-post.service.ts
- src/app/services/user-profile.service.ts
- #188 Pathの整理
- 全体的に１つ１つのPathに違和感があったので修正してみました。
Pathに違和感などあればご指摘いただきたいです。
> 全体的にPathの変更

- src/app/home/attention/attention.component.html
- src/app/home/attention/attention.component.scss
- src/app/home/new/new.component.html
- src/styles/_job-card.scss
- src/styles/_job-post.scss
- #298 文言修正
- 文言を日本語に修正
- 文字間隔修正
> card文言修正 ,、文字間隔修正 #298

- src/app/app.component.ts
- src/app/company-job-list/company-job-list/company-job-list.component.ts
- src/app/company-profile/company-profile/company-profile.component.ts
- src/app/detail/detail/detail.component.ts
- src/app/intl/about/about.component.ts
- src/app/intl/comlaw/comlaw.component.ts
- src/app/intl/help/help.component.ts
- src/app/intl/privacy/privacy.component.ts
- src/app/intl/terms/terms.component.ts
- src/app/job-list/job-list/job-list.component.ts
- src/app/keep/keep/keep.component.ts
- src/app/mypage/mypage/mypage.component.ts
- src/app/not-found/not-found.component.ts
- src/app/plan/plan/plan.component.ts
- src/app/search-result/search-result.component.ts
- #321 プロフィール作成しなくてもいいねできてしまう
- プロフィール作成しなくてもいいねできてしまうのでいいねできてしまうと、いいねしたユーザーリストでエラーが出てしまうので、条件分岐でユーザープロフィールが存在しなかったからいいねできない実装をしました。
> プロフィールを登録しないといいねできない仕様の実装

- .firebaserc
- src/environments/environment.prod.ts
- #294 Firebase／本番環境作成
- Firebase、Algoliaだけ本番環境の作成を行いました。
> productionモード（本番環境）作成

- src/app/home/top/top.component.html
- #334 リンク切れ修正
- 求人一覧ページのリンクが404になっていたので修正しました。
> リンク切れ修正 #334

- .github/workflows/jobs.yml
> refactor(jobs.yml)--prodに変更

- src/app/auth-dialog/auth-dialog.component.html
- src/app/company-profile/company-profile/company-profile.component.html
- src/app/create-company-profile/register-form/register-form.component.html
- src/app/create-user-profile/profile/profile.component.html
- src/app/delete-dialog/delete-dialog.component.html
- src/app/detail/detail/detail.component.html
- src/app/header/header.component.html
- src/app/home/top/top.component.html
- src/app/intl/help/help.component.html
- src/app/not-found/not-found.component.html
- src/app/plan/plan/plan.component.html
- src/app/profile-dialog/profile-dialog.component.html
- src/app/recruitment/recruitment/recruitment.component.html
- src/app/search-input/search-input.component.html
- src/app/stripe/payment/payment.component.html
- src/app/stripe/stripe/stripe.component.html
- src/index.html
- #337 パフォーマンスの向上
- Accessibility、SEOの向上
- aria-labelを追加
> Accessibility, SEOの向上

- .github/workflows/jobs.yml
> PROJECT_ID:追記

- src/app/delete-dialog/delete-dialog.component.ts
- src/app/header/header.component.html
- src/app/interfaces/article.ts
- src/app/intl/about/about.component.html
- src/app/plan/plan/plan.component.html
- src/app/stripe/payment/payment.component.html
- src/app/stripe/stripe/stripe.component.html
- #340 エラーFIx
- スペルミスでエラーが10箇所以上出ていたのでその修正
> スペルミス（エラー修正）

- firestore.rules
- functions/src/index.ts
- functions/src/recuit-email.function.ts
- src/app/app-routing.module.ts
- src/app/detail/detail/detail.component.html
- src/app/detail/detail/detail.component.ts
- src/app/entry/entry-routing.module.ts
- src/app/entry/entry.module.ts
- src/app/entry/entry/entry.component.html
- src/app/entry/entry/entry.component.scss
- src/app/entry/entry/entry.component.spec.ts
- src/app/entry/entry/entry.component.ts
- src/app/interfaces/article.ts
- src/app/interfaces/profile.ts
- src/app/mypage/mypage/mypage.component.html
- src/app/recruitment/recruitment/recruitment.component.ts
- src/app/services/job-post.service.ts
- src/app/services/recuit.service.spec.ts
- src/app/services/recuit.service.ts
- #233 応募をするをクリックすると404になる
- 求人応募フォーム作成
- 求人応募フォームを企業側にメール送信
- 求人フォームを企業側に送ると同時にユーザーにも応募完了メール(応募フォームの内容付き)のメール送信
- 求人詳細画面で求人に対して応募しているかどうかの判定でボタンにdisabled追加
多くなってすみません。
お手数ですがご確認よろしくお願い致します。
> 応募フォーム作成、企業・ユーザーにメール送信

- src/app/footer/footer.component.html
> footerバグ修正 #364

- src/app/intl/about/about.component.html
> 不要なページ削除 #371
